# Convert NEUROVASC into MEDS-OWL

In [ ]:
import os
import joblib

NEUROVASC = "NEUROVASC"
ETL_OUTPUT = f"{NEUROVASC}/MEDS_cohort"
ETL_INTERMEDIATE = f"{NEUROVASC}/pre_MEDS"
ETL_INPUT = f"{NEUROVASC}/raw_input"
ETL_GRAPH = f"{NEUROVASC}/graph"
EXPORT_DIR = "exports/neurovasc"
ETL_LABELS = f"{EXPORT_DIR}/labels"

os.makedirs(ETL_INPUT, exist_ok=True)
os.makedirs(ETL_INTERMEDIATE, exist_ok=True)
os.makedirs(ETL_OUTPUT, exist_ok=True)
os.makedirs(ETL_GRAPH, exist_ok=True)
os.makedirs(ETL_LABELS, exist_ok=True)

NUM_PATIENTS = 10000
TIME_OPT = "NT"
SYN_NEUROVASC_DATA = "https://raw.githubusercontent.com/TeamHeKA/neurovasc/refs/heads/main/exp/data/syn_data_10000.csv"

### a) Load/Generate source dataset

In [ ]:
import pandas as pd

# from NEUROVASC.utils.synthetic_generator import generate_synthetic_dataset
# df_input = generate_synthetic_dataset(NUM_PATIENTS, output_csv=f"{ETL_INPUT}/syn_data.csv")
df_input = pd.read_csv(SYN_NEUROVASC_DATA, index_col=0)
df_input = df_input.sample(frac=1, random_state=42).reset_index(drop=True)
df_input = df_input.rename(columns={"output": "outcome"})

### b) Preprocess the source dataset

In [ ]:
from NEUROVASC.utils.pre_MEDS import generate_meds_preprocessed

joblib.dump(
    df_input["outcome"].astype(int).to_list(),
    f"{ETL_LABELS}/outcomes_meds_{TIME_OPT}_{NUM_PATIENTS}_{0}.joblib",
)

df_input_outcome = df_input.iloc[0:NUM_PATIENTS]
df_input_no_outcome = df_input_outcome.drop(columns=["outcome"])
generate_meds_preprocessed(df_input_no_outcome, output_path=ETL_INTERMEDIATE)

print("Neurovasc data ready for MEDS-Extract")

### c) Run MEDS_Extract ETL to convert source into MEDS

In [ ]:
from MEDS_transforms.runner import main
import shutil

shutil.rmtree(ETL_OUTPUT)

main(
    [
        "pkg://MEDS_extract.configs._extract.yaml",
        "--overrides",
        f"input_dir={ETL_INTERMEDIATE}",
        f"output_dir={ETL_OUTPUT}",
        f"event_conversion_config_fp={NEUROVASC}/MESSY.yaml",
        "dataset.name=Neurovasc",
        "dataset.version=1.0",
    ]
)

### d) Convert NEUROVASC_MEDS into KG through MEDS2RDF

In [ ]:
from pathlib import Path

from meds2rdf import MedsRDFConverter
from meds2rdf.sinks import NTriplesSink
from meds2rdf.config import Config, MEDSSchema

shacl_graph = "https://raw.githubusercontent.com/TeamHeKA/meds-ontology/refs/heads/main/shacl/meds-shapes.ttl"

engine = MedsRDFConverter(ETL_OUTPUT)


engine.convert(
    sink=NTriplesSink(Path(EXPORT_DIR), gzip_mode=True),
    cfg=Config(schemas={MEDSSchema.CODES}),
)

# sink = GraphSink(graph=Graph())
# sink.graph.serialize(f"{ETL_GRAPH}/meds_{TIME_OPT}_{NUM_PATIENTS}.nt", format="nt")

In [ ]:
import glob
import gzip
from rdflib import Graph

g = Graph()

for path in glob.glob(f"{EXPORT_DIR}/*.nt.gz"):
    with gzip.open(path, "rt", encoding="utf-8") as f:
        g.parse(f, format="nt")

### e) Compute metrics [OPTIONAL]

In [ ]:
from NEUROVASC.utils.metrics import (
    compute_MEDS_graph_metrics_for_neurovasc,
    save_stats_json,
)
from pathlib import Path

stats = compute_MEDS_graph_metrics_for_neurovasc(
    MEDS_ETL_output_path=ETL_OUTPUT,
    graph=g,
    tabular_data=df_input_no_outcome,
    MEDS_intermediate=Path(ETL_INTERMEDIATE),
)

save_stats_json(stats, f"{ETL_OUTPUT}/metrics/all_metrics_2.json")

### f) Compute consistency checks [OPTIONAL]

In [ ]:
import polars as pl
from NEUROVASC.utils.neurovasc_meta import EVENTS_COLUMNS
from NEUROVASC.utils.transformers import (
    build_neurovasc_meds_dt,
    build_neurovasc_medskg_dt,
    check_dts_consistency,
)

synt_df = df_input.copy()
synt_df[EVENTS_COLUMNS] = (synt_df[EVENTS_COLUMNS] > -1).astype(int)

mimic_outcomes = joblib.load(
    f"{ETL_GRAPH}/outcomes_meds_{TIME_OPT}_{NUM_PATIENTS}.joblib"
)

meds_data = pl.read_parquet(str(f"{ETL_OUTPUT}/data/**/*.parquet")).to_dicts()
meds_df = build_neurovasc_meds_dt(meds_data)
meds_df = meds_df.astype(synt_df.dtypes.to_dict())
meds_df["outcome"] = mimic_outcomes

graph_df = build_neurovasc_medskg_dt(g)
graph_df = graph_df.astype(synt_df.dtypes.to_dict())
graph_df["outcome"] = mimic_outcomes


def remove_digits(_df: pd.DataFrame):
    _df["hospital_stay_length"] = _df["hospital_stay_length"].round()
    _df["nb_acte"] = _df["nb_acte"].round()
    _df["age"] = _df["age"].round()
    _df["gcs"] = _df["gcs"].round(2)


for _df in [synt_df, meds_df, graph_df]:
    remove_digits(_df)

check_dts_consistency(meds_df, synt_df)
check_dts_consistency(meds_df, graph_df)
check_dts_consistency(graph_df, synt_df)

# Convert MIMIC-IV Demo into MEDS-OWL
[link](https://physionet.org/content/mimic-iv-demo-meds/0.0.1/) to Physionet repository

In [ ]:
!bash MIMIC/run.sh

In [1]:
import os

MIMIC_ETL_OUTPUT = "MIMIC/MEDS_cohort"
MIMIC_ETL_GRAPH = f"{MIMIC_ETL_OUTPUT}/graph"
MIMIC_TASKS_PATH = "MIMIC/tasks"
TIME_OPT = "TS"

os.makedirs(MIMIC_ETL_GRAPH, exist_ok=True)

In [ ]:
names = []
for f in os.listdir(MIMIC_TASKS_PATH):
    f_name = os.path.splitext(f)[0]
    !aces-cli \
        config_path="{MIMIC_TASKS_PATH}/{f}" \
        cohort_name="{f_name}" \
        cohort_dir="{MIMIC_ETL_OUTPUT}/labels" \
        data=sharded \
        data.standard=meds \
        data.root="{MIMIC_ETL_OUTPUT}/data" \
        data.shard=$(expand_shards train/292 tuning/37 held_out/37) \
        -m
    names.append(f_name)

[2026-04-02 14:36:36,547][HYDRA] Launching 366 jobs locally
[2026-04-02 14:36:36,548][HYDRA] 	#0 : config_path=MIMIC/tasks/myocardial_infarction_1-5y_phenotyping.yaml cohort_name=myocardial_infarction_1-5y_phenotyping cohort_dir=MIMIC/MEDS_cohort/labels data=sharded data.standard=meds data.root=MIMIC/MEDS_cohort/data data.shard=train/0
[2026-04-02 14:36:36,653][aces.run][INFO] - Loading config from 'MIMIC/tasks/myocardial_infarction_1-5y_phenotyping.yaml'
[2026-04-02 14:36:36,658][aces.config][INFO] - Parsing windows...
[2026-04-02 14:36:36,658][aces.config][INFO] - Parsing trigger event...
[2026-04-02 14:36:36,658][aces.config][INFO] - Parsing predicates...
[2026-04-02 14:36:36,665][aces.run][INFO] - Attempting to get predicates dataframe given:
standard: meds
ts_format: '%m/%d/%Y %H:%M'
root: MIMIC/MEDS_cohort/data
shard: train/0
path: ${data.root}/${data.shard}.parquet
_prefix: /${data.shard}

[2026-04-02 14:36:36,666][aces.predicates][INFO] - Loading MEDS data...
[2026-04-02 14:36:36,946][aces.predicates][INFO] - Generating plain predicate columns...
[2026-04-02 14:36:36,957][aces.predicates][INFO] - Added predicate column 'MI'.
[2026-04-02 14:36:36,967][aces.predicates][INFO] - Added predicate column 'hospital_admission'.
[2026-04-02 14:36:36,967][aces.predicates][INFO] - Cleaning up predicates dataframe...
[2026-04-02 14:36:37,078][aces.predicates][INFO] - Loaded plain predicates. Generating derived predicate columns...
[2026-04-02 14:36:37,078][aces.predicates][INFO] - Generating special predicate columns...
[2026-04-02 14:36:37,082][aces.predicates][INFO] - Added predicate column '_ANY_EVENT'.
[2026-04-02 14:36:37,082][aces.query][INFO] - Checking if '(subject_id, timestamp)' columns are unique...
[2026-04-02 14:36:37,098][aces.utils][INFO] -
trigger
┣━━ target.start
┃   ┗━━ target.end
┃       ┗━━ censoring.end
┣━━ input.start
┗━━ gap.end

[2026-04-02 14:36:37,098][aces.query][INFO] - Beginning query...
[2026-04-02 14:36:37,099][aces.query][INFO] - No static variable criteria specified, removing all rows with null timestamps...
[2026-04-02 14:36:37,101][aces.query][INFO] - Identifying possible trigger nodes based on the specified trigger event...
[2026-04-02 14:36:37,102][aces.constraints][INFO] - Excluding 210,694 rows as they failed to satisfy '1 <= hospital_admission <= None'.
[2026-04-02 14:36:37,104][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'target.start'...
[2026-04-02 14:36:37,233][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'target.end'...
[2026-04-02 14:36:37,320][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'censoring.end'...
[2026-04-02 14:36:37,542][aces.constraints][INFO] - Excluding 1,290 rows as they failed to satisfy '1 <= _ANY_EVENT <= None'.
[2026-04-02 14:36:37,561][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'input.start'...
[2026-04-02 14:36:37,641][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'gap.end'...
[2026-04-02 14:36:37,802][aces.constraints][INFO] - Excluding 18 rows as they failed to satisfy 'None <= MI <= 0'.
[2026-04-02 14:36:37,814][aces.query][INFO] - Done. 157 valid rows returned corresponding to 76 subjects.
[2026-04-02 14:36:37,815][aces.query][INFO] - Extracting label 'MI' from window 'target'...
[2026-04-02 14:36:37,815][aces.query][INFO] - Setting index timestamp as 'end' of window 'input'...
[2026-04-02 14:36:37,819][aces.run][WARNING] - Output contains columns that are not valid MEDS label columns. For now, we are dropping them.
If you need these columns, please comment on https://github.com/justin13601/ACES/issues/97
Columns:
  - trigger
  - target.start_summary
  - target.end_summary
  - censoring.end_summary
  - input.start_summary
  - gap.end_summary
[2026-04-02 14:36:37,825][aces.run][INFO] - Completed in 0:00:01.171896. Results saved to 'MIMIC/MEDS_cohort/labels/myocardial_infarction_1-5y_phenotyping/train/0.parquet'.
[2026-04-02 14:36:37,827][HYDRA] 	#1 : config_path=MIMIC/tasks/myocardial_infarction_1-5y_phenotyping.yaml cohort_name=myocardial_infarction_1-5y_phenotyping cohort_dir=MIMIC/MEDS_cohort/labels data=sharded data.standard=meds data.root=MIMIC/MEDS_cohort/data data.shard=train/1
[2026-04-02 14:36:37,943][aces.run][INFO] - Loading config from 'MIMIC/tasks/myocardial_infarction_1-5y_phenotyping.yaml'
[2026-04-02 14:36:37,948][aces.config][INFO] - Parsing windows...
[2026-04-02 14:36:37,949][aces.config][INFO] - Parsing trigger event...
[2026-04-02 14:36:37,949][aces.config][INFO] - Parsing predicates...
[2026-04-02 14:36:37,950][aces.run][INFO] - Attempting to get predicates dataframe given:
standard: meds
ts_format: '%m/%d/%Y %H:%M'
root: MIMIC/MEDS_cohort/data
shard: train/1
path: ${data.root}/${data.shard}.parquet
_prefix: /${data.shard}

[2026-04-02 14:36:37,952][aces.predicates][INFO] - Loading MEDS data...
[2026-04-02 14:36:38,093][aces.predicates][INFO] - Generating plain predicate columns...
[2026-04-02 14:36:38,101][aces.predicates][INFO] - Added predicate column 'MI'.
[2026-04-02 14:36:38,109][aces.predicates][INFO] - Added predicate column 'hospital_admission'.
[2026-04-02 14:36:38,109][aces.predicates][INFO] - Cleaning up predicates dataframe...
[2026-04-02 14:36:38,219][aces.predicates][INFO] - Loaded plain predicates. Generating derived predicate columns...
[2026-04-02 14:36:38,220][aces.predicates][INFO] - Generating special predicate columns...
[2026-04-02 14:36:38,222][aces.predicates][INFO] - Added predicate column '_ANY_EVENT'.
[2026-04-02 14:36:38,222][aces.query][INFO] - Checking if '(subject_id, timestamp)' columns are unique...
[2026-04-02 14:36:38,235][aces.utils][INFO] -
trigger
┣━━ target.start
┃   ┗━━ target.end
┃       ┗━━ censoring.end
┣━━ input.start
┗━━ gap.end

[2026-04-02 14:36:38,235][aces.query][INFO] - Beginning query...
[2026-04-02 14:36:38,235][aces.query][INFO] - No static variable criteria specified, removing all rows with null timestamps...
[2026-04-02 14:36:38,238][aces.query][INFO] - Identifying possible trigger nodes based on the specified trigger event...
[2026-04-02 14:36:38,239][aces.constraints][INFO] - Excluding 222,814 rows as they failed to satisfy '1 <= hospital_admission <= None'.
[2026-04-02 14:36:38,240][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'target.start'...
[2026-04-02 14:36:38,444][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'target.end'...
[2026-04-02 14:36:38,526][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'censoring.end'...
[2026-04-02 14:36:38,749][aces.constraints][INFO] - Excluding 1,294 rows as they failed to satisfy '1 <= _ANY_EVENT <= None'.
[2026-04-02 14:36:38,766][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'input.start'...
[2026-04-02 14:36:38,849][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'gap.end'...
[2026-04-02 14:36:38,975][aces.constraints][INFO] - Excluding 18 rows as they failed to satisfy 'None <= MI <= 0'.
[2026-04-02 14:36:38,986][aces.query][INFO] - Done. 185 valid rows returned corresponding to 77 subjects.
[2026-04-02 14:36:38,986][aces.query][INFO] - Extracting label 'MI' from window 'target'...
[2026-04-02 14:36:38,987][aces.query][INFO] - Setting index timestamp as 'end' of window 'input'...
[2026-04-02 14:36:38,990][aces.run][WARNING] - Output contains columns that are not valid MEDS label columns. For now, we are dropping them.
If you need these columns, please comment on https://github.com/justin13601/ACES/issues/97
Columns:
  - trigger
  - target.start_summary
  - target.end_summary
  - censoring.end_summary
  - input.start_summary
  - gap.end_summary
[2026-04-02 14:36:38,995][aces.run][INFO] - Completed in 0:00:01.051352. Results saved to 'MIMIC/MEDS_cohort/labels/myocardial_infarction_1-5y_phenotyping/train/1.parquet'.
[2026-04-02 14:36:38,996][HYDRA] 	#2 : config_path=MIMIC/tasks/myocardial_infarction_1-5y_phenotyping.yaml cohort_name=myocardial_infarction_1-5y_phenotyping cohort_dir=MIMIC/MEDS_cohort/labels data=sharded data.standard=meds data.root=MIMIC/MEDS_cohort/data data.shard=train/2
[2026-04-02 14:36:39,108][aces.run][INFO] - Loading config from 'MIMIC/tasks/myocardial_infarction_1-5y_phenotyping.yaml'
[2026-04-02 14:36:39,113][aces.config][INFO] - Parsing windows...
[2026-04-02 14:36:39,114][aces.config][INFO] - Parsing trigger event...
[2026-04-02 14:36:39,114][aces.config][INFO] - Parsing predicates...
[2026-04-02 14:36:39,115][aces.run][INFO] - Attempting to get predicates dataframe given:
standard: meds
ts_format: '%m/%d/%Y %H:%M'
root: MIMIC/MEDS_cohort/data
shard: train/2
path: ${data.root}/${data.shard}.parquet
_prefix: /${data.shard}

[2026-04-02 14:36:39,116][aces.predicates][INFO] - Loading MEDS data...
[2026-04-02 14:36:39,272][aces.predicates][INFO] - Generating plain predicate columns...
[2026-04-02 14:36:39,280][aces.predicates][INFO] - Added predicate column 'MI'.
[2026-04-02 14:36:39,289][aces.predicates][INFO] - Added predicate column 'hospital_admission'.
[2026-04-02 14:36:39,289][aces.predicates][INFO] - Cleaning up predicates dataframe...
[2026-04-02 14:36:39,417][aces.predicates][INFO] - Loaded plain predicates. Generating derived predicate columns...
[2026-04-02 14:36:39,418][aces.predicates][INFO] - Generating special predicate columns...
[2026-04-02 14:36:39,420][aces.predicates][INFO] - Added predicate column '_ANY_EVENT'.
[2026-04-02 14:36:39,421][aces.query][INFO] - Checking if '(subject_id, timestamp)' columns are unique...
[2026-04-02 14:36:39,440][aces.utils][INFO] -
trigger
┣━━ target.start
┃   ┗━━ target.end
┃       ┗━━ censoring.end
┣━━ input.start
┗━━ gap.end

[2026-04-02 14:36:39,441][aces.query][INFO] - Beginning query...
[2026-04-02 14:36:39,441][aces.query][INFO] - No static variable criteria specified, removing all rows with null timestamps...
[2026-04-02 14:36:39,444][aces.query][INFO] - Identifying possible trigger nodes based on the specified trigger event...
[2026-04-02 14:36:39,446][aces.constraints][INFO] - Excluding 236,075 rows as they failed to satisfy '1 <= hospital_admission <= None'.
[2026-04-02 14:36:39,448][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'target.start'...
[2026-04-02 14:36:39,609][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'target.end'...
[2026-04-02 14:36:39,694][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'censoring.end'...
[2026-04-02 14:36:39,952][aces.constraints][INFO] - Excluding 1,289 rows as they failed to satisfy '1 <= _ANY_EVENT <= None'.
[2026-04-02 14:36:39,971][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'input.start'...
[2026-04-02 14:36:40,048][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'gap.end'...
[2026-04-02 14:36:40,237][aces.constraints][INFO] - Excluding 23 rows as they failed to satisfy 'None <= MI <= 0'.
[2026-04-02 14:36:40,248][aces.query][INFO] - Done. 143 valid rows returned corresponding to 75 subjects.
[2026-04-02 14:36:40,248][aces.query][INFO] - Extracting label 'MI' from window 'target'...
[2026-04-02 14:36:40,249][aces.query][WARNING] - All labels in the extracted cohort are the same: '0'. This may indicate an issue with the task logic. Please double-check your configuration file if this is not expected.
[2026-04-02 14:36:40,249][aces.query][INFO] - Setting index timestamp as 'end' of window 'input'...
[2026-04-02 14:36:40,252][aces.run][WARNING] - Output contains columns that are not valid MEDS label columns. For now, we are dropping them.
If you need these columns, please comment on https://github.com/justin13601/ACES/issues/97
Columns:
  - trigger
  - target.start_summary
  - target.end_summary
  - censoring.end_summary
  - input.start_summary
  - gap.end_summary
[2026-04-02 14:36:40,257][aces.run][INFO] - Completed in 0:00:01.148087. Results saved to 'MIMIC/MEDS_cohort/labels/myocardial_infarction_1-5y_phenotyping/train/2.parquet'.
[2026-04-02 14:36:40,258][HYDRA] 	#3 : config_path=MIMIC/tasks/myocardial_infarction_1-5y_phenotyping.yaml cohort_name=myocardial_infarction_1-5y_phenotyping cohort_dir=MIMIC/MEDS_cohort/labels data=sharded data.standard=meds data.root=MIMIC/MEDS_cohort/data data.shard=train/3
[2026-04-02 14:36:40,376][aces.run][INFO] - Loading config from 'MIMIC/tasks/myocardial_infarction_1-5y_phenotyping.yaml'
[2026-04-02 14:36:40,381][aces.config][INFO] - Parsing windows...
[2026-04-02 14:36:40,382][aces.config][INFO] - Parsing trigger event...
[2026-04-02 14:36:40,382][aces.config][INFO] - Parsing predicates...
[2026-04-02 14:36:40,383][aces.run][INFO] - Attempting to get predicates dataframe given:
standard: meds
ts_format: '%m/%d/%Y %H:%M'
root: MIMIC/MEDS_cohort/data
shard: train/3
path: ${data.root}/${data.shard}.parquet
_prefix: /${data.shard}

[2026-04-02 14:36:40,384][aces.predicates][INFO] - Loading MEDS data...
[2026-04-02 14:36:40,497][aces.predicates][INFO] - Generating plain predicate columns...
[2026-04-02 14:36:40,503][aces.predicates][INFO] - Added predicate column 'MI'.
[2026-04-02 14:36:40,511][aces.predicates][INFO] - Added predicate column 'hospital_admission'.
[2026-04-02 14:36:40,511][aces.predicates][INFO] - Cleaning up predicates dataframe...
[2026-04-02 14:36:40,582][aces.predicates][INFO] - Loaded plain predicates. Generating derived predicate columns...
[2026-04-02 14:36:40,582][aces.predicates][INFO] - Generating special predicate columns...
[2026-04-02 14:36:40,585][aces.predicates][INFO] - Added predicate column '_ANY_EVENT'.
[2026-04-02 14:36:40,586][aces.query][INFO] - Checking if '(subject_id, timestamp)' columns are unique...
[2026-04-02 14:36:40,597][aces.utils][INFO] -
trigger
┣━━ target.start
┃   ┗━━ target.end
┃       ┗━━ censoring.end
┣━━ input.start
┗━━ gap.end

[2026-04-02 14:36:40,598][aces.query][INFO] - Beginning query...
[2026-04-02 14:36:40,598][aces.query][INFO] - No static variable criteria specified, removing all rows with null timestamps...
[2026-04-02 14:36:40,600][aces.query][INFO] - Identifying possible trigger nodes based on the specified trigger event...
[2026-04-02 14:36:40,601][aces.constraints][INFO] - Excluding 185,755 rows as they failed to satisfy '1 <= hospital_admission <= None'.
[2026-04-02 14:36:40,602][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'target.start'...
[2026-04-02 14:36:40,702][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'target.end'...
[2026-04-02 14:36:40,764][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'censoring.end'...
[2026-04-02 14:36:41,007][aces.constraints][INFO] - Excluding 1,221 rows as they failed to satisfy '1 <= _ANY_EVENT <= None'.
[2026-04-02 14:36:41,023][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'input.start'...
[2026-04-02 14:36:41,105][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'gap.end'...
[2026-04-02 14:36:41,217][aces.constraints][INFO] - Excluding 16 rows as they failed to satisfy 'None <= MI <= 0'.
[2026-04-02 14:36:41,228][aces.query][INFO] - Done. 200 valid rows returned corresponding to 77 subjects.
[2026-04-02 14:36:41,229][aces.query][INFO] - Extracting label 'MI' from window 'target'...
[2026-04-02 14:36:41,229][aces.query][INFO] - Setting index timestamp as 'end' of window 'input'...
[2026-04-02 14:36:41,233][aces.run][WARNING] - Output contains columns that are not valid MEDS label columns. For now, we are dropping them.
If you need these columns, please comment on https://github.com/justin13601/ACES/issues/97
Columns:
  - trigger
  - target.start_summary
  - target.end_summary
  - censoring.end_summary
  - input.start_summary
  - gap.end_summary
[2026-04-02 14:36:41,241][aces.run][INFO] - Completed in 0:00:00.864066. Results saved to 'MIMIC/MEDS_cohort/labels/myocardial_infarction_1-5y_phenotyping/train/3.parquet'.
[2026-04-02 14:36:41,242][HYDRA] 	#4 : config_path=MIMIC/tasks/myocardial_infarction_1-5y_phenotyping.yaml cohort_name=myocardial_infarction_1-5y_phenotyping cohort_dir=MIMIC/MEDS_cohort/labels data=sharded data.standard=meds data.root=MIMIC/MEDS_cohort/data data.shard=train/4
[2026-04-02 14:36:41,357][aces.run][INFO] - Loading config from 'MIMIC/tasks/myocardial_infarction_1-5y_phenotyping.yaml'
[2026-04-02 14:36:41,363][aces.config][INFO] - Parsing windows...
[2026-04-02 14:36:41,363][aces.config][INFO] - Parsing trigger event...
[2026-04-02 14:36:41,363][aces.config][INFO] - Parsing predicates...
[2026-04-02 14:36:41,365][aces.run][INFO] - Attempting to get predicates dataframe given:
standard: meds
ts_format: '%m/%d/%Y %H:%M'
root: MIMIC/MEDS_cohort/data
shard: train/4
path: ${data.root}/${data.shard}.parquet
_prefix: /${data.shard}

[2026-04-02 14:36:41,366][aces.predicates][INFO] - Loading MEDS data...
[2026-04-02 14:36:41,558][aces.predicates][INFO] - Generating plain predicate columns...
[2026-04-02 14:36:41,569][aces.predicates][INFO] - Added predicate column 'MI'.
[2026-04-02 14:36:41,577][aces.predicates][INFO] - Added predicate column 'hospital_admission'.
[2026-04-02 14:36:41,577][aces.predicates][INFO] - Cleaning up predicates dataframe...
[2026-04-02 14:36:41,671][aces.predicates][INFO] - Loaded plain predicates. Generating derived predicate columns...
[2026-04-02 14:36:41,671][aces.predicates][INFO] - Generating special predicate columns...
[2026-04-02 14:36:41,682][aces.predicates][INFO] - Added predicate column '_ANY_EVENT'.
[2026-04-02 14:36:41,682][aces.query][INFO] - Checking if '(subject_id, timestamp)' columns are unique...
[2026-04-02 14:36:41,700][aces.utils][INFO] -
trigger
┣━━ target.start
┃   ┗━━ target.end
┃       ┗━━ censoring.end
┣━━ input.start
┗━━ gap.end

[2026-04-02 14:36:41,701][aces.query][INFO] - Beginning query...
[2026-04-02 14:36:41,701][aces.query][INFO] - No static variable criteria specified, removing all rows with null timestamps...
[2026-04-02 14:36:41,703][aces.query][INFO] - Identifying possible trigger nodes based on the specified trigger event...
[2026-04-02 14:36:41,704][aces.constraints][INFO] - Excluding 222,350 rows as they failed to satisfy '1 <= hospital_admission <= None'.
[2026-04-02 14:36:41,705][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'target.start'...
[2026-04-02 14:36:41,838][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'target.end'...
[2026-04-02 14:36:41,908][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'censoring.end'...
[2026-04-02 14:36:42,149][aces.constraints][INFO] - Excluding 1,254 rows as they failed to satisfy '1 <= _ANY_EVENT <= None'.
[2026-04-02 14:36:42,165][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'input.start'...
[2026-04-02 14:36:42,249][aces.extract_subtree][INFO] - Summarizing subtree rooted at 'gap.end'...
[2026-04-02 14:36:42,372][aces.constraints][INFO] - Excluding 14 rows as they failed to satisfy 'None <= MI <= 0'.
[2026-04-02 14:36:42,386][aces.query][INFO] - Done. 265 valid rows returned corresponding to 87 subjects.
[2026-04-02 14:36:42,386][aces.query][INFO] - Extracting label 'MI' from window 'target'...
[2026-04-02 14:36:42,386][aces.query][WARNING] - All labels in the extracted cohort are the same: '0'. This may indicate an issue with the task logic. Please double-check your configuration file if this is not expected.
[2026-04-02 14:36:42,387][aces.query][INFO] - Setting index timestamp as 'end' of window 'input'...
[2026-04-02 14:36:42,390][aces.run][WARNING] - Output contains columns that are not valid MEDS label columns. For now, we are dropping them.
If you need these columns, please comment on https://github.com/justin13601/ACES/issues/97
Columns:
  - trigger
  - target.start_summary
  - target.end_summary
  - censoring.end_summary
  - input.start_summary
  - gap.end_summary
[2026-04-02 14:36:42,396][aces.run][INFO] - Completed in 0:00:01.037684. Results saved to 'MIMIC/MEDS_cohort/labels/myocardial_infarction_1-5y_phenotyping/train/4.parquet'.

In [ ]:
from MIMIC.utils import PREFIX_MAP, process_codes

process_codes(
    input_parquet=f"{MIMIC_ETL_OUTPUT}/metadata/codes.parquet",
    output_dir="mimic_external_codes",
    prefix_map=PREFIX_MAP,
)

In [2]:
import os

MIMIC_ETL_OUTPUT = "MIMIC/MEDS_cohort"
MIMIC_ETL_GRAPH = f"{MIMIC_ETL_OUTPUT}/graph"
MIMIC_TASKS_PATH = "MIMIC/tasks"
TIME_OPT = "TS"

os.makedirs(MIMIC_ETL_GRAPH, exist_ok=True)

In [3]:
import os
import polars as pl

import joblib

from meds2rdf import MedsRDFConverter
from meds2rdf.sinks import NTriplesSink
from meds2rdf.config import Config, MEDSSchema
from pathlib import Path

TMP_DIR = f"{MIMIC_ETL_OUTPUT}/tmp"
TMP_DATA_DIR = f"{TMP_DIR}/data/train"
TMP_METADATA_DIR = f"{TMP_DIR}/metadata"

os.makedirs(TMP_DATA_DIR, exist_ok=True)
os.makedirs(TMP_METADATA_DIR, exist_ok=True)
os.makedirs(MIMIC_ETL_GRAPH, exist_ok=True)

In [4]:
NUM_PATIENTS = 10000
N_FOLDS = 1

# long_term_reccurrence
# inhospital_mortality (# 3_329 M 2_666 T, # 62_376 M 76_782 F)
# imminent_mortality (# 125497 T  79353 F)

# los_in_hospital_24h
# los_in_icu_24h
# mortality_in_hospital_48h
# mortality_in_icu_48h
# readmission_30d_in_icu_48h
# readmission_30d_in_hospital_48h

# first_24_in_icu_mortality
# first_24_in_hospital_mortality
TASK = "first_24_in_hospital_mortality"
IHM = f"{MIMIC_ETL_OUTPUT}/labels/{TASK}/**/*.parquet"
EXPORT_DIR = f"exports/{TASK}"
LABELS_DIR = f"{EXPORT_DIR}/labels"
os.makedirs(EXPORT_DIR, exist_ok=True)
os.makedirs(LABELS_DIR, exist_ok=True)

In [4]:
from MIMIC.utils2 import generate_samples

metadata = []

for f in os.listdir(MIMIC_TASKS_PATH):
    f_name = os.path.splitext(f)[0]
    if f_name != "first_24_in_icu_mortality":
        continue
    IHM = f"{MIMIC_ETL_OUTPUT}/labels/{f_name}/**/*.parquet"
    print(IHM)

    outcomes = pl.scan_parquet(IHM).select(
        "subject_id", "prediction_time", "boolean_value"
    )

    tt = (
        outcomes.filter(pl.col("boolean_value"))
        # .sort(pl.col("prediction_time"), descending=False)
        # .group_by("subject_id")
        # .head(1)
        .group_by("subject_id")
        .agg(pl.all().sample(n=1, seed=144))
        .explode(pl.all().exclude("subject_id"))
        .collect(engine="streaming")
    )

    metadata.append(
        {
            # "false_values": outcomes.filter(~pl.col("boolean_value")).count().collect(engine="streaming")["boolean_value"][0],
            "total_patients": outcomes.group_by("subject_id")
            .head(1)
            .count()
            .collect(engine="streaming")["subject_id"][0],
            "unique_true_values": len(tt),
            "unique_false_values": len(
                (
                    outcomes.filter(~pl.col("boolean_value"))
                    .join(
                        tt.select("subject_id").lazy(),
                        on="subject_id",
                        how="anti",
                    )
                    # .sort(pl.col("prediction_time"), descending=False)
                    # .group_by("subject_id")
                    # .head(1)
                    .group_by("subject_id")
                    .agg(pl.all().sample(n=1, seed=144))
                    .explode(pl.all().exclude("subject_id"))
                    .collect(engine="streaming")
                )
            ),
            "task": f_name,
            # "window": "24h",
            # "agg": "6h"
        }
    )

MIMIC/MEDS_cohort/labels/first_24_in_icu_mortality/**/*.parquet

In [8]:
display(metadata)

[{'total_patients': 44044,
  'unique_true_values': 4384,
  'unique_false_values': 39660,
  'task': 'first_24_in_icu_mortality'}]

In [5]:
samples_config = [
    {
        "metadata": {
            "true_values": 11179,
            "false_values": 389123,
            "total_patients": 165113,
            "unique_true_values": 10718,
            "unique_false_values": 154395,
        },
        "task": "first_24_in_hospital_mortality",
        "sample_size": 20000,
        "num_of_samples": 5,
        "fixed_true": False,
        "window": "24h",
        "agg": "12h",
    },
    {
        "metadata": {
            "true_values": 13430,
            "false_values": 367643,
            "total_patients": 148165,
            "unique_true_values": 12505,
            "unique_false_values": 135660,
        },
        "task": "first_48_in_hospital_mortality",
        "sample_size": 20000,
        "num_of_samples": 5,
        "fixed_true": False,
        "window": "48h",
        "agg": "1d",
    },
    {
        "metadata": {
            "true_values": 210837,
            "false_values": 255951,
            "total_patients": 204850,
            "unique_true_values": 125497,
            "unique_false_values": 79353,
        },
        "task": "first_48_in_hospital_los",
        "sample_size": 20000,
        "num_of_samples": 5,
        "fixed_true": True,
        "window": "48h",
        "agg": "12h",
    },
    {
        "metadata": {
            "total_patients": 44044,
            "unique_true_values": 4384,
            "unique_false_values": 39660,
        },
        "task": "first_24_in_icu_mortality",
        "sample_size": 8768,
        "num_of_samples": 5,
        "fixed_true": True,
        "window": "24h",
        "agg": "12h",
    },
    {
        "metadata": {
            "true_values": 4536,
            "false_values": 61254,
            "total_patients": 47942,
            "unique_true_values": 4333,
            "unique_false_values": 43609,
        },
        "task": "first_48_in_icu_mortality",
        "sample_size": 8666,
        "num_of_samples": 5,
        "fixed_true": True,
        "window": "48h",
        "agg": "1d",
    },
    {
        "metadata": {
            "true_values": 46935,
            "false_values": 31044,
            "total_patients": 56850,
            "unique_true_values": 38329,
            "unique_false_values": 18521,
        },
        "task": "first_48_in_icu_los",
        "sample_size": 7408,
        "num_of_samples": 5,
        "fixed_true": False,
        "window": "48h",
        "agg": "12h",
    },
    {
        "metadata": {
            "true_values": 3029,
            "false_values": 31187,
            "total_patients": 6071,
            "unique_true_values": 938,
            "unique_false_values": 5133,
        },
        "sample_size": 1876,
        "num_of_samples": 5,
        "fixed_true": True,
        "task": "ckd_in_diabetics_within_5y_of_kidney_panel",
        "window": "full",
        "agg": "1d",
    },
    {
        "metadata": {
            "true_values": 94656,
            "false_values": 324236,
            "total_patients": 145367,
            "unique_true_values": 40488,
            "unique_false_values": 104879,
        },
        "sample_size": 10000,
        "num_of_samples": 5,
        "fixed_true": False,
        "task": "readmission_30d",
        "window": "full",
        "agg": "1w",
    },
    {
        "metadata": {
            "true_values": 13147,
            "false_values": 521505,
            "total_patients": 218379,
            "unique_true_values": 11260,
            "unique_false_values": 207119,
        },
        "task": "post_hospital_discharge_mortality_30d",
        "sample_size": 5000,
        "num_of_samples": 5,
        "fixed_true": False,
        "window": "full",
        "agg": "1w",
    },
    {
        "metadata": {
            "true_values": 1312,
            "false_values": 76809,
            "total_patients": 30499,
            "unique_true_values": 443,
            "unique_false_values": 30056,
        },
        "task": "myocardial_infarction_1-5y_phenotyping",
        "sample_size": 886,
        "num_of_samples": 5,
        "fixed_true": True,
        "window": "full",
        "agg": "1d",
    },
    {
        "metadata": {
            "true_values": 65024,
            "false_values": 469628,
            "total_patients": 218379,
            "unique_true_values": 29732,
            "unique_false_values": 188647,
        },
        "task": "post_hospital_discharge_mortality_1y",
        "sample_size": 10000,
        "num_of_samples": 5,
        "fixed_true": False,
        "window": "full",
        "agg": "1mo",
    },
]

In [ ]:
from MIMIC.utils2 import generate_samples
from MIMIC.utils2 import *
import yaml

with open("experiments.yaml", "r") as f:
    config = yaml.safe_load(f)

events = pl.scan_parquet(
    f"{MIMIC_ETL_OUTPUT}/data/**/*.parquet", low_memory=True
).select("subject_id", "time", "code", "numeric_value", "text_value")

window_dict = {
    "24h": pl.col("time").is_null()
    | (
        (pl.col("time") >= (pl.col("prediction_time") - pl.duration(days=1)))
        & (pl.col("time") <= pl.col("prediction_time"))
    ),
    "48h": pl.col("time").is_null()
    | (
        (pl.col("time") >= (pl.col("prediction_time") - pl.duration(days=2)))
        & (pl.col("time") <= pl.col("prediction_time"))
    ),
    "full": pl.col("time").is_null() | (pl.col("time") <= pl.col("prediction_time")),
}

for group_name, experiments in config["experiments"].items():
    print(f"\n=== Group: {group_name} ===")

    for scfg in experiments:
        print(f"Running task: {scfg['task']}")
        IHM = f"{MIMIC_ETL_OUTPUT}/labels/{scfg['task']}/**/*.parquet"
        outcomes = pl.scan_parquet(IHM).select(
            "subject_id", "prediction_time", "boolean_value"
        )

        samples = generate_samples(
            labels=outcomes,
            n_folds=scfg["num_of_samples"],
            size=scfg["sample_size"],
            seed=1234,
            fixed_true=scfg["fixed_true"],
        )

        for index, sample in enumerate([samples[0]]):
            events_base = (
                events.join(sample.lazy(), on="subject_id", how="inner")
                .with_columns(remove_long_text)
                .with_columns(birthdate_to_age)
                .filter(window_dict[scfg["window"]])
            )

            freq_codes = (
                events_base.group_by("code")
                .len()
                .filter(pl.col("len") > (pl.col("len").quantile(0.15)))
                .select("code")
            )

            events_base = (
                events_base.join(
                    freq_codes, on="code", how="semi"
                )  # .join(less_freq_codes, on="code", how="inner")
                .with_columns(parsed=parse_txt_to_float)
                .with_columns(swap_text_with_numeric)
                # .with_columns(numeric_value=swap_text_with_numeric[0])
                # .with_columns(text_value=swap_text_with_numeric[1])
                # keep original code/text for grouping after explosion
                .with_columns(orig_code=pl.col("code"), orig_text=pl.col("text_value"))
                # create the list-of-values to explode
                .with_columns(bp_values=bp_values_list)
                # explode -> if BP valid you'll get 2 rows, otherwise 1 row
                .explode("bp_values")
                # set the numeric_value from the exploded element
                .with_columns(numeric_value=pl.col("bp_values"))
                # assign new code names for BP rows using a windowed max over the original group
                .with_columns(code=to_systolic_and_dyastolic_pressure)
                # set text_value to null for the BP-derived rows, keep other text_value unchanged
                .with_columns(text_value=set_BP_values_text_to_null)
                # cleanup helper columns
                .drop(derived_columns)
                .with_columns(regenerate_ids)
            )

            agg = (
                events_base.with_columns(
                    # Create a 6-hour time bin
                    (pl.col("time").dt.truncate(scfg["agg"])).alias(
                        "time"
                    )  # rename here directly
                )
                .group_by(["subject_id", "code", "time"])
                .agg(
                    [
                        pl.col("numeric_value")
                        .mean()
                        .alias("numeric_value"),  # average numeric values
                        pl.col("text_value")
                        .first()
                        .alias("text_value"),  # keep the first text value
                        pl.col("prediction_time").first().alias("prediction_time"),
                        pl.col("boolean_value").first().alias("boolean_value"),
                    ]
                )
                .sort(["subject_id", "time"])
            ).collect(engine="streaming")

            EXPORT_DIR = f"exports/{scfg['task']}"
            LABELS_DIR = f"{EXPORT_DIR}/labels"
            os.makedirs(EXPORT_DIR, exist_ok=True)
            os.makedirs(LABELS_DIR, exist_ok=True)

            import shutil

            TMP_DIR_EXP = f"{MIMIC_ETL_OUTPUT}/tmp_{scfg['task']}_{index}"
            TMP_DATA_DIR_EXP = f"{TMP_DIR_EXP}/data/train"
            os.makedirs(TMP_DIR_EXP, exist_ok=True)
            os.makedirs(TMP_DATA_DIR_EXP, exist_ok=True)
            shutil.copytree(TMP_METADATA_DIR, f"{TMP_DIR_EXP}/metadata", dirs_exist_ok=True)

            os.makedirs(MIMIC_ETL_GRAPH, exist_ok=True)

            # lenn = len(agg)
            # if lenn > 7_000_000:
            #     print(
            #         f"[TOOO BIG]: {scfg['task']}: {lenn} | #codes: {len(freq_codes.collect(engine='streaming'))}"
            #     )
            # else:
            #     print(
            #         f"[OK]: {scfg['task']}: {lenn} | #codes: {len(freq_codes.collect(engine='streaming'))}"
            #     )

            # joblib.dump(
            #     value=extract_labels_array(agg),
            #     filename=f"{LABELS_DIR}/outcomes_meds_{TIME_OPT}_{scfg['sample_size']}_{index}.joblib",
            # )

            # agg.select(
            #     ["subject_id", "code", "time", "numeric_value", "text_value"]
            # ).write_parquet(f"{TMP_DATA_DIR_EXP}/0.parquet")

            # MedsRDFConverter(TMP_DIR_EXP).convert(
            #     sink=NTriplesSink(
            #         Path(f"{EXPORT_DIR}/meds_{scfg['sample_size']}_{index}"), gzip_mode=True
            #     ),
            #     cfg=Config(schemas={MEDSSchema.CODES}),
            # )

=== Group: mortality ===
Running task: first_24_in_hospital_mortality

shape: (10, 7)
┌────────────┬──────────────┬──────────────┬──────────────┬────────────┬─────────────┬─────────────┐
│ subject_id ┆ code         ┆ time         ┆ numeric_valu ┆ text_value ┆ prediction_ ┆ boolean_val │
│ ---        ┆ ---          ┆ ---          ┆ e            ┆ ---        ┆ time        ┆ ue          │
│ u32        ┆ str          ┆ datetime[μs] ┆ ---          ┆ str        ┆ ---         ┆ ---         │
│            ┆              ┆              ┆ f64          ┆            ┆ datetime[μs ┆ bool        │
│            ┆              ┆              ┆              ┆            ┆ ]           ┆             │
╞════════════╪══════════════╪══════════════╪══════════════╪════════════╪═════════════╪═════════════╡
│ 0          ┆ GENDER//M    ┆ null         ┆ null         ┆ null       ┆ 2213-04-19  ┆ true        │
│            ┆              ┆              ┆              ┆            ┆ 18:47:00    ┆             │
│ 0          ┆ MEDS_BIRTH   ┆ null         ┆ 62.339131    ┆ null       ┆ 2213-04-19  ┆ true        │
│            ┆              ┆              ┆              ┆            ┆ 18:47:00    ┆             │
│ 0          ┆ MEDICATION// ┆ 2213-04-18   ┆ null         ┆ null       ┆ 2213-04-19  ┆ true        │
│            ┆ START//Metha ┆ 12:00:00     ┆              ┆            ┆ 18:47:00    ┆             │
│            ┆ done         ┆              ┆              ┆            ┆             ┆             │
│ 0          ┆ MEDICATION// ┆ 2213-04-18   ┆ null         ┆ null       ┆ 2213-04-19  ┆ true        │
│            ┆ Sodium       ┆ 12:00:00     ┆              ┆            ┆ 18:47:00    ┆             │
│            ┆ Chloride 0.… ┆              ┆              ┆            ┆             ┆             │
│ 0          ┆ MEDICATION// ┆ 2213-04-18   ┆ null         ┆ null       ┆ 2213-04-19  ┆ true        │
│            ┆ START//Hyosc ┆ 12:00:00     ┆              ┆            ┆ 18:47:00    ┆             │
│            ┆ yamine       ┆              ┆              ┆            ┆             ┆             │
│ 0          ┆ MEDICATION// ┆ 2213-04-18   ┆ null         ┆ null       ┆ 2213-04-19  ┆ true        │
│            ┆ Methadone//A ┆ 12:00:00     ┆              ┆            ┆ 18:47:00    ┆             │
│            ┆ dminis…      ┆              ┆              ┆            ┆             ┆             │
│ 0          ┆ MEDICATION// ┆ 2213-04-18   ┆ null         ┆ null       ┆ 2213-04-19  ┆ true        │
│            ┆ START//Finas ┆ 12:00:00     ┆              ┆            ┆ 18:47:00    ┆             │
│            ┆ teride       ┆              ┆              ┆            ┆             ┆             │
│ 0          ┆ MEDICATION// ┆ 2213-04-18   ┆ null         ┆ null       ┆ 2213-04-19  ┆ true        │
│            ┆ START//Senna ┆ 12:00:00     ┆              ┆            ┆ 18:47:00    ┆             │
│ 0          ┆ MEDICATION// ┆ 2213-04-18   ┆ null         ┆ null       ┆ 2213-04-19  ┆ true        │
│            ┆ START//Omepr ┆ 12:00:00     ┆              ┆            ┆ 18:47:00    ┆             │
│            ┆ azole        ┆              ┆              ┆            ┆             ┆             │
│ 0          ┆ MEDICATION// ┆ 2213-04-18   ┆ null         ┆ null       ┆ 2213-04-19  ┆ true        │
│            ┆ Acetaminophe ┆ 12:00:00     ┆              ┆            ┆ 18:47:00    ┆             │
│            ┆ n//Adm…      ┆              ┆              ┆            ┆             ┆             │
└────────────┴──────────────┴──────────────┴──────────────┴────────────┴─────────────┴─────────────┘

Running task: first_48_in_hospital_mortality

In [ ]:
from MIMIC.utils2 import *
import pandas as pd

window_dict = {
    "24h": pl.col("time").is_null() | (
        (pl.col("time") >= (pl.col("prediction_time") - pl.duration(days=1)))
        & (pl.col("time") <= pl.col("prediction_time"))
    ),
    "48h": pl.col("time").is_null() | (
        (pl.col("time") >= (pl.col("prediction_time") - pl.duration(days=2)))
        & (pl.col("time") <= pl.col("prediction_time"))
    ),
    "full": pl.col("time").is_null() | (pl.col("time") <= pl.col("prediction_time"))
}

events = pl.scan_parquet(
    f"{MIMIC_ETL_OUTPUT}/data/**/*.parquet", low_memory=True
).select("subject_id", "time", "code", "numeric_value", "text_value")

events_base = (
    events.join(samples[0].lazy(), on="subject_id", how="inner")
    .with_columns(remove_long_text)
    .with_columns(birthdate_to_age)
    .filter(window_dict[])
)

freq_codes = (
    events_base.group_by("code")
    .len()
    .filter(pl.col("len") > (NUM_PATIENTS / 10))
    .select("code")
)

In [ ]:
events_base = (
    events_base.join(
        freq_codes, on="code", how="semi"
    )  # .join(less_freq_codes, on="code", how="inner")
    .with_columns(parsed=parse_txt_to_float)
    .with_columns(swap_text_with_numeric)
    # .with_columns(numeric_value=swap_text_with_numeric[0])
    # .with_columns(text_value=swap_text_with_numeric[1])
    # keep original code/text for grouping after explosion
    .with_columns(orig_code=pl.col("code"), orig_text=pl.col("text_value"))
    # create the list-of-values to explode
    .with_columns(bp_values=bp_values_list)
    # explode -> if BP valid you'll get 2 rows, otherwise 1 row
    .explode("bp_values")
    # set the numeric_value from the exploded element
    .with_columns(numeric_value=pl.col("bp_values"))
    # assign new code names for BP rows using a windowed max over the original group
    .with_columns(code=to_systolic_and_dyastolic_pressure)
    # set text_value to null for the BP-derived rows, keep other text_value unchanged
    .with_columns(text_value=set_BP_values_text_to_null)
    # cleanup helper columns
    .drop(derived_columns)
    .with_columns(regenerate_ids)
)

In [25]:
agg = (
    events_base.with_columns(
        # Create a 6-hour time bin
        (pl.col("time").dt.truncate("6h")).alias("time")  # rename here directly
    )
    .group_by(["subject_id", "code", "time"])
    .agg(
        [
            pl.col("numeric_value")
            .mean()
            .alias("numeric_value"),  # average numeric values
            pl.col("text_value")
            .first()
            .alias("text_value"),  # keep the first text value
            pl.col("prediction_time").first().alias("prediction_time"),
            pl.col("boolean_value").first().alias("boolean_value"),
        ]
    )
    .sort(["subject_id", "time"])
)

In [26]:
agg = agg.collect(engine="streaming")

In [27]:
display(agg)

shape: (2_703_847, 7)
┌────────────┬──────────────┬──────────────┬──────────────┬────────────┬─────────────┬─────────────┐
│ subject_id ┆ code         ┆ time         ┆ numeric_valu ┆ text_value ┆ prediction_ ┆ boolean_val │
│ ---        ┆ ---          ┆ ---          ┆ e            ┆ ---        ┆ time        ┆ ue          │
│ u32        ┆ str          ┆ datetime[μs] ┆ ---          ┆ str        ┆ ---         ┆ ---         │
│            ┆              ┆              ┆ f64          ┆            ┆ datetime[μs ┆ bool        │
│            ┆              ┆              ┆              ┆            ┆ ]           ┆             │
╞════════════╪══════════════╪══════════════╪══════════════╪════════════╪═════════════╪═════════════╡
│ 0          ┆ GENDER//M    ┆ null         ┆ null         ┆ null       ┆ 2151-05-14  ┆ false       │
│            ┆              ┆              ┆              ┆            ┆ 01:18:00    ┆             │
│ 0          ┆ MEDS_BIRTH   ┆ null         ┆ 20.378231    ┆ null       ┆ 2151-05-14  ┆ false       │
│            ┆              ┆              ┆              ┆            ┆ 01:18:00    ┆             │
│ 0          ┆ HOSPITAL_DIS ┆ 2151-05-13   ┆ null         ┆ null       ┆ 2151-05-14  ┆ false       │
│            ┆ CHARGE//UNK  ┆ 18:00:00     ┆              ┆            ┆ 01:18:00    ┆             │
│ 0          ┆ TRANSFER_TO/ ┆ 2151-05-13   ┆ null         ┆ null       ┆ 2151-05-14  ┆ false       │
│            ┆ /admit//Emer ┆ 18:00:00     ┆              ┆            ┆ 01:18:00    ┆             │
│            ┆ gency …      ┆              ┆              ┆            ┆             ┆             │
│ 0          ┆ TRANSFER_TO/ ┆ 2151-05-13   ┆ null         ┆ null       ┆ 2151-05-14  ┆ false       │
│            ┆ /discharge// ┆ 18:00:00     ┆              ┆            ┆ 01:18:00    ┆             │
│            ┆ UNKNOW…      ┆              ┆              ┆            ┆             ┆             │
│ …          ┆ …            ┆ …            ┆ …            ┆ …          ┆ …           ┆ …           │
│ 9999       ┆ LAB//51301// ┆ 2143-01-21   ┆ null         ┆ null       ┆ 2143-01-21  ┆ true        │
│            ┆ K/uL         ┆ 06:00:00     ┆              ┆            ┆ 08:31:00    ┆             │
│ 9999       ┆ LAB//51250// ┆ 2143-01-21   ┆ null         ┆ null       ┆ 2143-01-21  ┆ true        │
│            ┆ fL           ┆ 06:00:00     ┆              ┆            ┆ 08:31:00    ┆             │
│ 9999       ┆ LAB//51248// ┆ 2143-01-21   ┆ null         ┆ null       ┆ 2143-01-21  ┆ true        │
│            ┆ pg           ┆ 06:00:00     ┆              ┆            ┆ 08:31:00    ┆             │
│ 9999       ┆ LAB//50893// ┆ 2143-01-21   ┆ null         ┆ null       ┆ 2143-01-21  ┆ true        │
│            ┆ mg/dL        ┆ 06:00:00     ┆              ┆            ┆ 08:31:00    ┆             │
│ 9999       ┆ LAB//50931// ┆ 2143-01-21   ┆ null         ┆ null       ┆ 2143-01-21  ┆ true        │
│            ┆ mg/dL        ┆ 06:00:00     ┆              ┆            ┆ 08:31:00    ┆             │
└────────────┴──────────────┴──────────────┴──────────────┴────────────┴─────────────┴─────────────┘

In [28]:
joblib.dump(
    value=extract_labels_array(agg),
    filename=f"{LABELS_DIR}/outcomes_meds_{TIME_OPT}_{NUM_PATIENTS}_{0}.joblib",
)

agg.select(["subject_id", "code", "time", "numeric_value", "text_value"]).write_parquet(
    f"{TMP_DATA_DIR}/0.parquet"
)

MedsRDFConverter(TMP_DIR).convert(
    sink=NTriplesSink(Path(f"{EXPORT_DIR}/meds_{NUM_PATIENTS}_{0}"), gzip_mode=True),
    cfg=Config(schemas={MEDSSchema.CODES}),
)

Processing Event: 100%|██████████| 11/11 [05:38<00:00, 30.79s/it]
Processing Code: 100%|██████████| 1/1 [00:03<00:00,  3.63s/it]

In [13]:
from MIMIC.utils2 import *

REMOVE_OCCURRENCES = 7

events = pl.scan_parquet(
    f"{MIMIC_ETL_OUTPUT}/data/**/*.parquet", low_memory=True
).select("subject_id", "time", "code", "numeric_value", "text_value")

for idx, sample in enumerate(samples):
    events_base = (
        events.join(sample.lazy(), on="subject_id", how="inner")
        .filter(before_prediction_time)
        .with_columns(remove_long_text)
    )

    most_frequent_codes = (
        events_base.select("code")
        .group_by("code")
        .agg(pl.len().alias("count"))
        .sort(pl.col("count"), descending=True)
        # .filter(pl.col("count") > pl.col("count").quantile(0.995))
        .with_columns((pl.col("count") / NUM_PATIENTS).alias("count_div"))
        .filter(pl.col("count_div") >= REMOVE_OCCURRENCES)
        .collect(engine="streaming")
    )

    events_with_ids = (
        events_base.join(most_frequent_codes.lazy(), on="code", how="anti")
        .with_columns(parsed=parse_txt_to_float)
        .with_columns(numeric_value=swap_text_with_numeric[0])
        .with_columns(text_value=swap_text_with_numeric[1])
        # keep original code/text for grouping after explosion
        .with_columns(orig_code=pl.col("code"), orig_text=pl.col("text_value"))
        # create the list-of-values to explode
        .with_columns(bp_values=bp_values_list)
        # explode -> if BP valid you'll get 2 rows, otherwise 1 row
        .explode("bp_values")
        # set the numeric_value from the exploded element
        .with_columns(numeric_value=pl.col("bp_values"))
        # assign new code names for BP rows using a windowed max over the original group
        .with_columns(code=to_systolic_and_dyastolic_pressure)
        # set text_value to null for the BP-derived rows, keep other text_value unchanged
        .with_columns(text_value=set_BP_values_text_to_null)
        # cleanup helper columns
        .drop(derived_columns)
        .with_columns(regenerate_ids)
        .collect(engine="streaming")
    )

    joblib.dump(
        value=extract_labels_array(events_with_ids),
        filename=f"{LABELS_DIR}/outcomes_meds_{TIME_OPT}_{NUM_PATIENTS}_{idx}.joblib",
    )

    events_with_ids.select(
        ["subject_id", "code", "time", "numeric_value", "text_value"]
    ).write_parquet(f"{TMP_DATA_DIR}/0.parquet")

    MedsRDFConverter(TMP_DIR).convert(
        sink=NTriplesSink(
            Path(f"{EXPORT_DIR}/meds_{NUM_PATIENTS}_{idx}"), gzip_mode=True
        ),
        cfg=Config(schemas={MEDSSchema.CODES}),
    )

Processing Event: 100%|██████████| 11/11 [05:45<00:00, 31.44s/it]
Processing Code: 100%|██████████| 1/1 [00:01<00:00,  1.55s/it]
Processing Event:  36%|███▋      | 4/11 [02:19<04:03, 34.81s/it]

KeyboardInterrupt:

In [ ]:
# import polars as pl

# df_vitals = pl.read_csv(
#     "https://raw.githubusercontent.com/MIT-LCP/mimic-code/main/mimic-iv/mapping/meas_chartevents_main.csv",
#     columns=["itemid (omop_source_code)"],
# )["itemid (omop_source_code)"].to_list()

# # vitals = [str(x) for x in df_vitals] + [
# #     "227969",
# #     "224650",
# #     "227958",
# #     "SUBJECT_WEIGHT_AT_INFUSION//KG",
# # ]

# bad_strings = ["___", "None", "N/A", "", " "]

# remove_long_text = (
#     pl.when(
#         (pl.col("text_value").is_in(bad_strings))
#         | (pl.col("text_value").str.len_chars() > 50)
#     )
#     .then(None)
#     .otherwise(pl.col("text_value"))
#     .alias("text_value")
# )

# before_prediction_time = (pl.col("time").is_null()) | (
#     pl.col("time") <= pl.col("prediction_time")
# )

# swap_text_with_numeric = (
#     pl.coalesce(pl.col("parsed"), pl.col("numeric_value")),
#     pl.when(pl.col("parsed").is_not_null()).then(None).otherwise(pl.col("text_value")),
# )

# parse_txt_to_float = pl.col("text_value").cast(pl.Float64, strict=False)

# regenerate_ids = (
#     pl.col("subject_id")
#     .cast(pl.Utf8)
#     .cast(pl.Categorical)
#     .to_physical()
#     .alias("subject_id")
# )

# # no_vitals = ~pl.col("code").str.contains_any(vitals)

# is_bp = pl.col("code") == "Blood Pressure"

# # quick sanity check: contains a slash + strict-looking numeric pattern "num/num"
# bp_text_valid = pl.col("text_value").is_not_null() & pl.col("text_value").str.contains(
#     r"^\s*\d+(\.\d+)?/\d+(\.\d+)?\s*$"
# )

# # produce a list: for Blood Pressure valid texts -> [high, low] (floats, sorted desc)
# # otherwise -> single-element list [numeric_value] so explode() yields one row for non-BP rows
# bp_values_list = (
#     pl.when(is_bp & bp_text_valid)
#     .then(
#         pl.col("text_value")
#         .str.strip_chars()
#         .str.split("/")
#         .list.eval(
#             pl.element().cast(pl.Float64, strict=False)
#         )  # cast both parts to float
#         .list.sort(descending=True)  # higher first
#     )
#     .otherwise(pl.concat_list([pl.col("numeric_value")]))
# )

In [ ]:
# import polars as pl

# top_99_codes = (
#     pl.scan_parquet(f"{MIMIC_ETL_OUTPUT}/data/**/*.parquet")
#     .select("subject_id", "code", "time")
#     .join(samples[0].lazy(), on="subject_id", how="inner")
#     .filter(before_prediction_time)
#     .group_by("code")
#     .agg(pl.len().alias("count"))
#     .sort(pl.col("count"), descending=True)
#     # .filter(pl.col("count") > pl.col("count").quantile(0.995))
#     .with_columns((pl.col("count") / len(samples[0])).alias("count_div"))
#     .filter(pl.col("count_div") >= 15)
#     .collect(engine="streaming")
# )

# display(top_99_codes)

# top_99_codes.select(
#     [
#         pl.col("count_div").quantile(0.1).alias("p1"),
#         pl.col("count_div").quantile(0.61).alias("p10"),
#         pl.col("count_div").quantile(0.61).alias("p20"),
#         pl.col("count_div").quantile(0.61).alias("p30"),
#         pl.col("count_div").quantile(0.61).alias("p40"),
#         pl.col("count_div").quantile(0.61).alias("p50"),
#         pl.col("count_div").quantile(0.61).alias("p60"),
#         pl.col("count_div").quantile(0.70).alias("p70"),
#         pl.col("count_div").quantile(0.80).alias("p80"),
#         pl.col("count_div").quantile(0.90).alias("p90"),
#         pl.col("count_div").quantile(1).alias("p100"),
#     ]
# )

# # top_99_codes.write_csv("all_events_count.csv")

In [ ]:
# import os
# import joblib
# from MIMIC.utils import get_labels

# from meds2rdf import MedsRDFConverter
# from meds2rdf.sinks import NTriplesSink
# from meds2rdf.config import Config, MEDSSchema
# from pathlib import Path


# TMP_DIR = f"{MIMIC_ETL_OUTPUT}/tmp"
# TMP_DATA_DIR = f"{TMP_DIR}/data/train"
# TMP_METADATA_DIR = f"{TMP_DIR}/metadata"
# EXPORT_DIR = f"exports/{TASK}"
# LABELS_DIR = f"{EXPORT_DIR}/labels"

# os.makedirs(TMP_DATA_DIR, exist_ok=True)
# os.makedirs(TMP_METADATA_DIR, exist_ok=True)
# os.makedirs(EXPORT_DIR, exist_ok=True)
# os.makedirs(LABELS_DIR, exist_ok=True)


# for idx, s in enumerate([samples[0]]):
#     idx = 15
#     n_patients = len(s)

#     events_with_ids = (
#         pl.scan_parquet(f"{MIMIC_ETL_OUTPUT}/data/**/*.parquet", low_memory=True)
#         .select("subject_id", "time", "code", "numeric_value", "text_value")
#         .with_columns(remove_long_text)
#         # .filter(no_vitals)
#         .join(s.lazy(), on="subject_id", how="inner")
#         .filter(before_prediction_time)
#         .join(top_99_codes.select("code").lazy(), on="code", how="anti")
#         .with_columns(parsed=parse_txt_to_float)
#         .with_columns(numeric_value=swap_text_with_numeric[0])
#         .with_columns(text_value=swap_text_with_numeric[1])
#         # keep original code/text for grouping after explosion
#         .with_columns(orig_code=pl.col("code"), orig_text=pl.col("text_value"))
#         # create the list-of-values to explode
#         .with_columns(bp_values=bp_values_list)
#         # explode -> if BP valid you'll get 2 rows, otherwise 1 row
#         .explode("bp_values")
#         # set the numeric_value from the exploded element
#         .with_columns(numeric_value=pl.col("bp_values"))
#         # assign new code names for BP rows using a windowed max over the original group
#         .with_columns(
#             code=pl.when(pl.col("orig_code").str.contains("Blood Pressure"))
#             .then(
#                 pl.when(
#                     pl.col("numeric_value")
#                     == pl.col("bp_values")
#                     .max()
#                     .over(["subject_id", "time", "orig_text"])
#                 )
#                 .then(pl.lit("Systolic blood pressure"))
#                 .otherwise(pl.lit("Diastolic blood pressure"))
#             )
#             .otherwise(pl.col("code"))
#         )
#         # set text_value to null for the BP-derived rows, keep other text_value unchanged
#         .with_columns(
#             text_value=pl.when(pl.col("orig_code").str.contains("Blood Pressure"))
#             .then(pl.lit(None).cast(pl.Utf8))
#             .otherwise(pl.col("text_value"))
#         )
#         # cleanup helper columns
#         .drop(["bp_values", "orig_code", "orig_text", "parsed"])
#         .with_columns(regenerate_ids)
#         .collect(engine="streaming")
#     )

#     print(events_with_ids.select("subject_id").__len__())

#     joblib.dump(
#         value=(
#             events_with_ids.group_by("subject_id")
#             .agg(pl.col("boolean_value").first().cast(pl.Int8).alias("boolean_value"))
#             .sort("subject_id")
#             .select("boolean_value")
#             .to_series()
#             .to_list()
#         ),
#         filename=f"{LABELS_DIR}/outcomes_meds_{TIME_OPT}_{n_patients}_{idx}.joblib",
#     )

#     events_with_ids.select(
#         ["subject_id", "code", "time", "numeric_value", "text_value"]
#     ).write_parquet(f"{TMP_DATA_DIR}/0.parquet")

#     MedsRDFConverter(TMP_DIR).convert(
#         sink=NTriplesSink(
#             Path(f"{EXPORT_DIR}/meds_{n_patients}_{idx}"), gzip_mode=True
#         ),
#         cfg=Config(schemas={MEDSSchema.CODES}),
#     )

# # ['insurance', 'language', 'marital_status', 'race', 'hadm_id', 'drg_severity', 'drg_mortality', 'emar_seq',
# #'priority', 'route', 'frequency', 'doses_per_24_hrs', 'unit', 'ordercategorydescription', 'statusdescription']

# # " 1902091"
# # " 3343150"
# # " 6387103" >=23
# # " 5206213" 100
# # " 6094968" 0.998 23% less
# # " 9382849"  0.99
# # " 5548428"  0.98
# # "21655442"  1.00

In [ ]:
from rdflib import Graph
from NEUROVASC.utils.metrics import compute_MEDS_graph_metrics, save_stats_json

MIMIC_OUTPUT_GRAPH = f"{MIMIC_ETL_GRAPH}/meds_{TIME_OPT}_{NUM_PATIENTS}.nt"

g = Graph()
g.parse(MIMIC_OUTPUT_GRAPH, format="nt")

stats = compute_MEDS_graph_metrics(
    MEDS_ETL_output_path=MIMIC_ETL_OUTPUT,
    graph=g,
)

save_stats_json(stats, f"{MIMIC_ETL_OUTPUT}/metrics/all_metrics.json")

In [ ]:
# TODO create a sparql query to get (subject_id, time, code, numeric_value)

# import polars as pl
# from NEUROVASC.utils.transformers import build_neurovasc_meds_dt, build_neurovasc_medskg_dt, check_dts_consistency

# mimic_data = pl.read_parquet(str(f"{MIMIC_ETL_OUTPUT}/data/**/*.parquet")).to_dicts()
# check_dts_consistency(meds_df, graph_df)

# NEUROVASC 2.0

In [ ]:
import os

N2 = "NEUROVASC2"
N2_ETL_OUTPUT = f"{N2}/MEDS_cohort"
N2_ETL_INTERMEDIATE = f"{N2}/pre_MEDS"
N2_ETL_INPUT = f"{N2}/raw_input"
N2_ETL_GRAPH = f"{N2}/graph"

os.makedirs(N2_ETL_INPUT, exist_ok=True)
os.makedirs(N2_ETL_INTERMEDIATE, exist_ok=True)
os.makedirs(N2_ETL_OUTPUT, exist_ok=True)
os.makedirs(N2_ETL_GRAPH, exist_ok=True)

TIME_OPT = "NT"

In [ ]:
import pandas as pd

# from NEUROVASC.utils.synthetic_generator import generate_synthetic_dataset
# df_input = generate_synthetic_dataset(NUM_PATIENTS, output_csv=f"{ETL_INPUT}/syn_data.csv")
df_input = pd.read_csv(f"{N2_ETL_INPUT}/synthetic_data_sdv.csv")
NUM_PATIENTS = len(set(df_input["ID_PAT"]))

In [ ]:
display(df_input)

In [ ]:
from NEUROVASC2.pre_MEDS import generate_meds_preprocessed

(patients, events, mimic_outcomes) = generate_meds_preprocessed(
    df_input,
    output_path=N2_ETL_INTERMEDIATE,
    outcome_path=f"{N2_ETL_GRAPH}/outcomes_meds_{TIME_OPT}_{NUM_PATIENTS}.joblib",
)

print("Neurovasc 2 data ready for MEDS-Extract")

In [ ]:
from MEDS_transforms.runner import main
import shutil

shutil.rmtree(N2_ETL_OUTPUT)

main(
    [
        "pkg://MEDS_extract.configs._extract.yaml",
        "--overrides",
        f"input_dir={N2_ETL_INTERMEDIATE}",
        f"output_dir={N2_ETL_OUTPUT}",
        f"event_conversion_config_fp={N2}/MESSY.yaml",
        "dataset.name=Neurovasc",
        "dataset.version=2.0",
    ]
)

In [ ]:
import polars as pl

meds_data = pl.read_parquet(str(f"{N2_ETL_OUTPUT}/data/**/*.parquet")).to_dicts()

In [ ]:
display(pd.DataFrame(meds_data))

In [ ]:
from meds2rdf import MedsRDFConverter

EXPORT_DIR = "exports/neurovasc_2_0"
ETL_LABELS = f"{EXPORT_DIR}/labels"


MedsRDFConverter(N2_ETL_OUTPUT).convert(
    sink=NTriplesSink(Path(f"{EXPORT_DIR}/meds_{NUM_PATIENTS}_{idx}"), gzip_mode=True),
    cfg=Config(schemas=MEDSSchema.all()),
)

In [ ]:
from rdflib import Graph
from NEUROVASC.utils.metrics import compute_MEDS_graph_metrics, save_stats_json

g = Graph()

for path in glob.glob(f"{EXPORT_DIR}/*.nt.gz"):
    with gzip.open(path, "rt", encoding="utf-8") as f:
        g.parse(f, format="nt")

stats = compute_MEDS_graph_metrics(
    MEDS_ETL_output_path=N2_ETL_OUTPUT,
    graph=g,
)

save_stats_json(stats, f"{N2_ETL_OUTPUT}/metrics/all_metrics.json")